// Generated by https://quicktype.io
export interface IUser {
  sub?: string;
  clientType?: string;
  branchid?: string;
  userId?: string;
  mngrUserId?: string;
  workingClass?: string;
  countryId?: string;
  countryCode?: string;
  bankId?: string;
  role?: string[];
  username?: string;
  displayName?: string[];
  source?: string;
  channel?: string;
  token_usage?: string;
  jti?: string;
  aud?: string[];
  nbf?: number;
  exp?: number;
  iat?: number;
  iss?: string;
}
