import { FIELD_TYPES } from '../../../shared-stubs/dynamic-form';

export const SUBSIDIARIES_WITH_PURPOSE_CODE = ['KE', 'CD', 'RW', 'UG', 'SS', 'TZ'];

export const ACCOUNT_DETAILS_FIELDS = [
  {
    id: 1,
    order: 1,
    key: 'FirstName',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.FIRST_NAME',
    value: '',
    readonly: true,
  },
  {
    id: 2,
    order: 2,
    key: 'LastName',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.LAST_NAME',
    value: '',
    readonly: true,
  },
  {
    id: 3,
    order: 3,
    key: 'FullName',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.FULL_NAME',
    value: '',
    readonly: true,
  },
  {
    id: 4,
    order: 4,
    key: 'IdNumber',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.ID_NUMBER',
    value: '',
    readonly: true,
  },
  {
    id: 5,
    order: 5,
    key: 'Cif',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.CIF',
    value: '',
    readonly: true,
  },
  {
    id: 6,
    order: 6,
    key: 'AccountNumber',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.ACCOUNT_NUMBER',
    value: '',
    readonly: true,
  },
  {
    id: 7,
    order: 7,
    key: 'AccountCurrency',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.ACCOUNT_CURRENCY',
    value: '',
    readonly: true,
  },
  {
    id: 8,
    order: 8,
    key: 'AccountBalance',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.ACCOUNT_BALANCE',
    value: '',
    readonly: true,
  },
  {
    id: 9,
    order: 9,
    key: 'MobileNumber',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.MOBILE_NUMBER',
    value: '',
    readonly: true,
  },
  {
    id: 10,
    order: 10,
    key: 'EmailAddress',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.EMAIL_ADDRESS',
    value: '',
    readonly: true,
  },
  {
    id: 11,
    order: 11,
    key: 'PostalAddress',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.POSTAL_ADDRESS',
    value: '',
    readonly: true,
  },
  {
    id: 12,
    order: 12,
    key: 'Mandate',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.MANDATE',
    value: '',
    readonly: true,
  },
  {
    id: 13,
    order: 13,
    key: 'IsGlAccount',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.IS_GL_ACCOUNT',
    value: '',
    readonly: true,
  },
];

export const REMITTER_ACC_DETAILS_FIELDS = [
  {
    id: 1,
    order: 1,
    key: 'NgWorkItemNo',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.NEWGEN_WORK_ITEM_NUMBER',
    value: '',
    readonly: true,
  },
  {
    id: 2,
    order: 2,
    key: 'InitiationDate',
    field_type: FIELD_TYPES.DATETIME,
    label: 'FIELDS.INITIATION_DATE',
    value: new Date(),
    readonly: true,
    disabled: true,
  },
  {
    id: 3,
    order: 3,
    key: 'UserName',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.USER_NAME',
    value: '',
    readonly: true,
  },
  {
    id: 4,
    order: 4,
    key: 'OneEquityNr',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.ONE_EQUITY_NUMBER',
    value: '',
    readonly: true,
  },
  {
    id: 5,
    order: 5,
    key: 'CountryCode',
    field_type: FIELD_TYPES.SELECT,
    label: 'FIELDS.COUNTRY_CODE',
    options: [
      { label: '11', value: 'SS' },
      { label: '43', value: 'CD' },
      { label: '50', value: 'RW' },
      { label: '54', value: 'KE' },
      { label: '55', value: 'TZ' },
      { label: '56', value: 'UG' },
    ],
    readonly: true,
    disabled: true,
  },
  {
    id: 6,
    order: 6,
    key: 'CenterNr',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.CENTER_NUMBER',
    value: '',
    readonly: true,
  },
  {
    id: 7,
    order: 7,
    key: 'RequestingBranch',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.REQUESTING_BRANCH',
    value: '',
    readonly: true,
  },
];

export const CHARGE_DETAILS_FIELDS = [
  {
    id: 1,
    order: 1,
    key: 'ChargeOption',
    field_type: FIELD_TYPES.SELECT,
    label: 'FIELDS.CHARGE_OPTION',
    value: '',
    required: true,
  },
  {
    id: 2,
    order: 2,
    key: 'Amount',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.CHARGE_AMOUNT',
    value: 0,
    readonly: true,
  },
  {
    id: 3,
    order: 3,
    key: 'AmountCurrency',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.CHARGE_AMOUNT_CURRENCY',
    value: '',
    readonly: true,
  },
  {
    id: 4,
    order: 4,
    key: 'NormalCharge',
    field_type: FIELD_TYPES.LINE_AMOUNT_FIELD,
    label: 'FIELDS.NORMAL_CHARGE',
    value: 0,
    readonly: true,
  },
  {
    id: 5,
    order: 5,
    key: 'VatAmount',
    field_type: FIELD_TYPES.LINE_AMOUNT_FIELD,
    label: 'FIELDS.VAT',
    value: 0,
    readonly: true,
  },
  {
    id: 6,
    order: 6,
    key: 'RscAmount',
    field_type: FIELD_TYPES.LINE_AMOUNT_FIELD,
    label: 'FIELDS.RSC',
    value: 0,
    readonly: true,
  },
  {
    id: 7,
    order: 7,
    key: 'SumOfCharges',
    field_type: FIELD_TYPES.LINE_AMOUNT_FIELD,
    label: 'FIELDS.SUM_OF_CHARGES',
    value: 0,
    readonly: true,
  },
];

export const ADDITIONAL_FIELDS = [
  {
    id: 1,
    order: 1,
    key: 'RemittanceInfo1',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.REMITTANCE_INFO_1',
    value: '',
    autocomplete: 'off',
  },
  {
    id: 2,
    order: 2,
    key: 'RemittanceInfo2',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.REMITTANCE_INFO_2',
    value: '',
    autocomplete: 'off',
  },
  {
    id: 3,
    order: 3,
    key: 'RemittanceInfo3',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.REMITTANCE_INFO_3',
    value: '',
    autocomplete: 'off',
  },
  {
    id: 4,
    order: 4,
    key: 'RemittanceInfo4',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.REMITTANCE_INFO_4',
    value: '',
    autocomplete: 'off',
  },
];

export const SENDER_TO_RECEIVER_INFORMATION_FIELDS = [
  {
    id: 1,
    order: 1,
    key: 'Line1',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.LINE_1',
    value: '',
    maximum: 15,
    autocomplete: 'off',
  },
  {
    id: 2,
    order: 2,
    key: 'Line2',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.LINE_2',
    value: '',
    maximum: 33,
    autocomplete: 'off',
  },
];

export const EXCHANGE_DETAILS_FIELDS = [
  {
    id: 1,
    order: 1,
    key: 'RateCode',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.RATE_CODE',
    value: '',
    readonly: true,
    required: true,
  },
  {
    id: 2,
    order: 2,
    key: 'ExchangeRate',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.EXCHANGE_RATE',
    value: '',
    readonly: true,
    required: true,
  },
  {
    id: 3,
    order: 3,
    key: 'BaseExchangeRate',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.BASE_EXCHANGE_RATE',
    value: '',
    readonly: true,
    required: true,
  },
  {
    id: 4,
    order: 4,
    key: 'TreasuryRate',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.TREASURY_RATE',
    value: '',
    readonly: true,
  },
  {
    id: 5,
    order: 5,
    key: 'TicketNumber',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.SPECIAL_RATE_COUPON_NUMBER',
    value: '',
    autocomplete: 'off',
  },
  {
    id: 6,
    order: 6,
    key: 'SearchByCif',
    field_type: FIELD_TYPES.HIDDEN,
    label: 'FIELDS.SEARCH_BY_CIF',
    value: '',
    readonly: true,
  },
  {
    id: 7,
    order: 7,
    key: 'ConvertedCurrency',
    field_type: FIELD_TYPES.LINE,
    label: 'FIELDS.CONVERTED_CURRENCY',
    value: '',
    readonly: true,
    required: true,
  },
  {
    id: 8,
    order: 8,
    key: 'ConvertedAmount',
    field_type: FIELD_TYPES.LINE_AMOUNT_FIELD,
    label: 'FIELDS.CONVERTED_AMOUNT',
    value: '',
    readonly: true,
    required: true,
  },
];
