export namespace SaveAndInvest {
  export interface NotificationDetails {
    sms: boolean;
    email: boolean;
  }

  export interface RecurrentPaymentSettings {
    amount: number;
    endDate: Date;
    frequencyOfPayment: string;
    startDate: Date;
  }

  export interface TaskData {
    customerPresent: boolean;
    notificationDetails: NotificationDetails;
    recurrentPaymentSettings?: RecurrentPaymentSettings;
    countryCode: string;
    initialSavingAmount: number;
    reference: string;
    savingsAmountCurrency: string;
    sourceAccount: string;
    termsAndConditionsAccepted: boolean;
    useRecurringPayment: boolean;
    sourceAccountSchemeType: string;
  }

  export interface CallDepositSavingRequest {
    associatedId: string;
    customerId: string;
    customerName: string;
    ParentTicketId: number | null;
    taskData: TaskData;
  }

  export interface FormDataCallDeposit {
    accountName: string;
    currency: string;
    initialAmount: number;
    debitAccount: string;
    debitAccountCurrency: string;
    paymentType: string;
    frequency: string;
    effectiveDate?: any;
    dayOrMonth: string;
    savingAmount: number;
    startDate: Date;
    endDate: Date;
    ParentTicketId: number | null;
  }

  export namespace Product {
    export interface LongDescription {
      title: string;
      description: string;
    }

    export interface MinimumDeposit {
      currency: string;
      minimumAmount: number;
    }

    export interface ProductCategory {
      name: string;
      description: string;
    }

    export interface ResponseObject {
      productId: number;
      name: string;
      shortDescription: string;
      longDescription: LongDescription[];
      minimumDeposits: MinimumDeposit[];
      productCategories: ProductCategory[];
      illustrationLink: string;
    }

    export interface Response {
      statusMessage: string;
      statusCode: string;
      successful: boolean;
      responseObject: ResponseObject[];
    }
  }
  export namespace Frequency {
    export interface ResponseObject {
      frequencyId: number;
      name: string;
      description: string;
    }

    export interface Response {
      statusMessage: string;
      statusCode: string;
      successful: boolean;
      responseObject: ResponseObject[];
    }
  }
  //#region
  export namespace TicketResponse {
    export interface RecurrentPaymentSettings {
      Amount: number;
      EndDate: Date;
      FrequencyOfPayment: string;
      StartDate: Date;
      NextExecutionDate: Date;
      ExecutionDay: number;
      SetUpStandingInstruction: boolean;
    }

    export interface NotificationDetails {
      Sms: boolean;
      Email: boolean;
    }

    export interface ContactDetails {
      PhoneNumber: string;
      Email: string;
      FirstName: string;
      LastName: string;
      MiddleName?: any;
      Title: string;
    }

    export interface GeneratedAccountInfo {
      AccountNumber: string;
      AccountCurrencyCode: string;
      CreationStatus?: any;
    }

    export interface Item3 {
      ParentTaskId?: any;
      AssociatedId?: any;
      Reference: string;
      ProductId: number;
      SourceAccount: string;
      SourceAccountSchemeType: string;
      InitialSavingAmount: number;
      TermsAndConditionsAccepted: boolean;
      UseRecurringPayment: boolean;
      SavingsAmountCurrency: string;
      CountryCode: string;
      RecurrentPaymentSettings: RecurrentPaymentSettings;
      CustomerPresent: boolean;
      AccountNumber?: any;
      ReferenceId?: any;
      NotificationDetails: NotificationDetails;
      ContactDetails: ContactDetails;
      CustomerId: string;
      BankId: string;
      BranchId: string;
      GeneratedAccountInfo: GeneratedAccountInfo;
    }

    export interface CallDeposit {
      Item1: boolean;
      Item2: string;
      Item3: Item3;
    }
  }

  //#endregion

  // Generated by https://quicktype.io

  export interface FormDataFixedDeposit {
    accountName: string;
    currency: string;
    initialAmount: number;
    depositTerm: string;
    customTerm: string;
    maturityDate: string;
    withdrawOrRollover: string;
    rolloverOption: any;
    debitAccount: string;
    debitAccountCurrency: string;
    effectiveDate: string;
    interestPercent: number;
    investmentReturns: number;
  }

  export interface FixedDespositSubmitPayload {
    associatedId: string;
    customerId: string;
    customerName: string;
    accountName: string;
    taskData: FidexDespositTaskData;
    ticketTaskData?: any;
  }

  export interface FidexDespositTaskData {
    customerPresent: boolean;
    notificationDetails: NotificationDetails;
    contactDetails: ContactDetails;
    depositAmount: number;
    investmentTermInMonths: number;
    productId: number;
    reference: string;
    rollOverOptionId: number;
    shouldRollerOverOnMaturity: boolean;
    sourceAccount: string;
    currencyCode: string;
    termsAndConditionsAccepted: boolean;
  }

  export interface ContactDetails {
    phoneNumber: string;
    email: string;
    firstName: string;
  }

  export interface DepositCustomerAccountsResponse {
    statusMessage: string;
    statusCode: string;
    successful: boolean;
    responseObject: CustomerAccountsResponseArray[];
  }

  export interface CustomerAccountsResponseArray {
    accountName: string;
    accountNumber: string;
    accountCurreny: string;
    accountType: string;
    accountDormant: string;
    availableBalance: number;
    hasMinimalAmount: boolean;
    schemeCode: string;
    schemeType: string;
  }

  export interface RollOverOptionsResponse {
    statusMessage: string;
    statusCode: string;
    successful: boolean;
    responseObject: RollOverResponseObjectArray[];
  }

  export interface FixedDespositSubmitPayload {
    associatedId: string;
    customerId: string;
    customerName: string;
    accountName: string;
    ParentTicketId: number | null;
    taskData: FidexDespositTaskData;
  }

  export interface FidexDespositTaskData {
    customerPresent: boolean;
    notificationDetails: NotificationDetails;
    contactDetails: ContactDetails;
    depositAmount: number;
    investmentTermInMonths: number;
    productId: number;
    reference: string;
    rollOverOptionId: number;
    shouldRollerOverOnMaturity: boolean;
    sourceAccount: string;
    currencyCode: string;
    termsAndConditionsAccepted: boolean;
    interestPercent: number;
    investmentReturns: number;
  }

  export interface ContactDetails {
    phoneNumber: string;
    email: string;
    firstName: string;
  }

  export interface NotificationDetails {
    sms: boolean;
    email: boolean;
  }

  export interface RollOverOptionsResponse {
    statusMessage: string;
    statusCode: string;
    successful: boolean;
    responseObject: RollOverResponseObjectArray[];
  }

  export interface RollOverResponseObjectArray {
    rollOverOptionId: number;
    name: string;
    description: string;
    financleEquivalent: string;
  }

  // Generated by https://quicktype.io

  export interface DepositCustomerAccountsResponse {
    statusMessage: string;
    statusCode: string;
    successful: boolean;
    responseObject: CustomerAccountsResponseArray[];
  }

  export interface CustomerAccountsResponseArray {
    accountName: string;
    accountNumber: string;
    accountCurreny: string;
    accountType: string;
    accountDormant: string;
    availableBalance: number;
    hasMinimalAmount: boolean;
  }

  export interface RollOverResponseObjectArray {
    rollOverOptionId: number;
    name: string;
    description: string;
    financleEquivalent: string;
  }

  // Generated by https://quicktype.io

  export interface InterestEstimateResponse {
    statusMessage: string;
    statusCode: string;
    successful: boolean;
    responseObject: InterestEstimateResponseData;
  }

  export interface InterestEstimateResponseData {
    interestRateInPercent: number;
    investmentReturns: number;
  }
}

export type DivendDisposalPreference =
  | 'Cheque'
  | 'Domestic bank'
  | 'International bank'
  | 'Draft'
  | 'Mobile payment'
  | 'Direct payments';
