// Generated by https://quicktype.io

export interface FidexSubmitPayload {
  associatedId: string;
  customerId: string;
  customerName: string;
  parentTicketId: number;
  taskData: TaskData;
}

export interface TaskData {
  customerPresent: boolean;
  notificationDetails: NotificationDetails;
  contactDetails: ContactDetails;
  depositAmount: number;
  investmentTermInMonths: number;
  productId: number;
  rate: number;
  reference: string;
  rollOverOptionId: number;
  shouldRollerOverOnMaturity: boolean;
  sourceAccount: string;
  currencyCode: string;
  termsAndConditionsAccepted: boolean;
}

export interface ContactDetails {
  phoneNumber: string;
  email: string;
  firstName: string;
}

export interface NotificationDetails {
  sms: boolean;
  email: boolean;
}
