export enum TransferType {
  OWNACCOUNT = 'OwnAccount',
  EQUITYACCOUNT = 'IntraBank', //'TransferToOtherEquityBankAccount'
  OTHERBANK = 'InterBank',
}

export interface ITransferTypeObject {
  value: TransferType;
  name: string;
}

// Generated by https://quicktype.io

export interface AccountResponse {
  statusMessage: string;
  statusCode: string;
  successful: boolean;
  responseObject: ResponseObject;
}

export interface ResponseObject {
  cif: string;
  title: string;
  firstName: string;
  lastName: string;
  shortName: string;
  gender: string;
  maritalStatus: string;
  phoneNumber1: string;
  phoneNumber2: string;
  email: string;
  dateOfBirth: string;
  postalCode: any;
  bankID: string;
  memo: string;
  identifications: Identification[];
  accounts: Account[];
  preferredAddress: PreferredAddress;
  avatarName?: string;
  datecreated?: string;
  kra?: string;
  id?: string;
  agentFunctions?: any;
  agentLimit?: string;
  email2?: string;
  backUrl?: string;
  isBshFunction?: boolean;
}

export interface Account {
  cif?: string;
  accountName?: string;
  accountNumber?: string;
  accountCurrency?: string;
  schemeType?: string;
  accountStatus?: string;
  schemeCode?: string;
  availableBalance?: string;
  effectiveBalance?: string;
  scheduleNo?: any;
  sanctionLimit?: string;
  flowAmmount?: string;
  mandate?: string;
  accountOpeningDate?: string;
  freezeCode?: string;
  freezeReasonCode?: string;
  lienAmmount?: string;
  remainingNumberOfInstalments?: any;
  percentCompleted?: number;
  nextPaymentDueInNumOfDays?: number;
  nextDueDate?: any;
  disbursedAmount?: string;
  disbursementAmountSpecified?: boolean;
  ecoCode?: any;
}

export interface Identification {
  id: string;
  type: string;
}

export interface PreferredAddress {
  address1: string;
  address2: string;
  cityCode: string;
  stateCode: string;
  countryCode: string;
  cityCodeDesc: string;
  pinCode: string;
}

// Generated by https://quicktype.io

export interface IAccMngtObj {
  cif: string;
  bankID: string;
  idNumber: string;
  accountsId: string;
  firstName: string;
  lastName: string;
  dateOfBirth: Date;
  idType: string;
}

// Generated by https://quicktype.io

export interface IFundsTransferFromData {
  currentCustomer: CurrentCustomer;
  transactionDetailsForm: TransactionDetailsForm;
  beneficiaryDetailsForm: BeneficiaryDetailsForm;
  paymentDetailsForm: PaymentDetailsForm;
  exchangeRateForm: ExchangeRateForm;
  instrumentForm: InstrumentForm;
  senderCurrency?: string;
}

export interface BeneficiaryDetailsForm {
  beneficiaryAccount: string;
  recepientName: string;
}

export interface CurrentCustomer {
  cif: string;
  bankID: string;
  idNumber: string;
  accountsId: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  idType: string;
}

export interface ExchangeRateForm {
  rateCode: string;
  exchangeRate: string;
  baseExchangeRate: string;
  convertedCurrency: string;
  convertedAmount: number;
}

export interface InstrumentForm {
  instrumentType: string;
  instrumentNumber: string;
  instrumentDate: string;
}

export interface PaymentDetailsForm {
  amountToSend: string;
  paymentReason: string;
  paymentCurrency: string;
}

export interface TransactionDetailsForm {
  associatedId: any;
  fee: string;
  transactionType: string;
  transferType: string;
  account: string;
  sms: boolean;
  email: boolean;
  skipBio: boolean;
}

// Generated by https://quicktype.io

export interface MoveMoneyPayload {
  SenderDetails: SenderDetails;
  BeneficiaryDetails: BeneficiaryDetails;
  TransactionDetails: TransactionDetails;
  ExchangeDetails: ExchangeDetails;
  NotificationDetails: NotificationDetails;
  Fee: string;
}

export interface BeneficiaryDetails {
  FullName: string;
  DestinationAccountType: string;
  DestinationAccountCurrency: string;
  BIC: string;
  BankName: string;
  Address: string;
  Email: string;
  Phone: string;
  Favorited: boolean;
  DestinationAccount: string;
}

export interface ExchangeDetails {
  RateCode: string;
  ExchangeRate: string;
  BaseExchangeRate: string;
  TreasuryRate: string;
  SearchByCif: string;
  ConvertedCurrency: string;
  ConvertedAmount: number;
  TicketNumber: string;
}

export interface NotificationDetails {
  Sms: boolean;
  Email: boolean;
}

export interface SenderDetails {
  AssociatedId: string;
  CustomerName: string;
  CustomerId: string;
  BankId: string;
  TransactionType: string;
  TransferType: string;
  SourceAccount: string;
  SourceAccountCurrency: string;
  CurrencyCode: string;
  Amount: number;
  PaymentReason: string;
  SkipBio: boolean;
}

export interface TransactionDetails {
  InstrumentType: string;
  InstrumentDate: string;
  InstrumentNumber: string;
}

// Generated by https://quicktype.io
