export interface ILocale {
  id: string;
  name: string;
}

// Generated by https://quicktype.io

export interface ICountryCode {
  countryCode: string;
  countryName: string;
  currency: null;
  currencySymbol: null;
  nationality: string;
  dialCode: string;
  flagPath: string;
  operatingCountry: boolean;
  countryCode3Chars: null;
  icon?: string;
}
