// Generated by https://quicktype.io
export enum RecipientOptions {
  CUSTOMER_ONLY = 0,
  BOTH = 1,
  ANOTHER_CONTACT = 2,
}

export enum BalacenCertificateStatus {
  CANPAY = 0,
  CANTPAYCHARGE = 1,
  CANTPAYTOTALCHARGE = 2,
}

export interface BalacenCertificatePayload {
  bankId: string;
  branchId: string;
  actionName: string;
  balanceDate: string;
  customerDetails: CustomerDetails;
  alternateAccountId: string;
  chargeOption: number;
  ParentTaskId?: any;
  emailOption?: string;
  reference: string;
}

export interface CustomerDetails {
  firstName: string;
  lastName: string;
  accountId: any;
  customerId: string;
  emailAddress: string;
  altEmailAddress: string;
}

export interface PayloadCalculateCharge {
  amount: number;
  bankId: string;
}

// Generated by https://quicktype.io

export interface ResponseCalculateCharge {
  statusMessage: string;
  statusCode: string;
  successful: boolean;
  responseObject: ResponseObjectCalculateCharge;
}

export interface ResponseObjectCalculateCharge {
  balCertFee: string;
  balCertComm: string;
  balCertDuty: string;
  currency: string;
  totalBalCertFee: string;
  totalCharge: string;
  totalbalCertComm: string;
  totalbalCertFee: string;
  balance: number;
  status: BalacenCertificateStatus;
}

// Generated by https://quicktype.io

export interface PayloadAccountBalance {
  accountId: string;
  bankId: string;
}

// Generated by https://quicktype.io
export interface ResponseAccountBalance {
  statusMessage: string;
  statusCode: string;
  successful: boolean;
  responseObject: ResponseObjectAccountBalance;
}

export interface ResponseObjectAccountBalance {
  message: string;
  date: string;
  balance: string;
}

// Generated by https://quicktype.io

export interface ResponseTicketBalanceCertificate {
  statusMessage: string;
  statusCode: string;
  successful: boolean;
  responseObject: ResponseObjectTicketBalanceCertificate;
}

export interface ResponseObjectTicketBalanceCertificate {
  taskTypeId: number;
  taskType: ActionFlow;
  actionFlowId: number;
  actionFlow: ActionFlow;
  taskData: string;
  status: string;
  taskDocuments: any[];
  taskNotes: any[];
  actions: Action[];
  createdBy: string;
  associatedId: string;
  userId: string;
  branchId: string;
  bankId: string;
  workItem: string;
  customerId: string;
  customerName: string;
  id: number;
  createdOnUtc: string;
  modifiedOnUtc: string;
  isDeleted: boolean;
}

interface ActionFlow {
  name: string;
  description: string;
  branchId?: string;
  isSequential?: boolean;
  id: number;
  createdOnUtc: string;
  modifiedOnUtc: string;
  isDeleted: boolean;
}

interface Action {
  taskId: number;
  actionTypeId: number;
  actionType: ActionFlow;
  status: string;
  order: number;
  error: null;
  isRepeatable: boolean;
  id: number;
  createdOnUtc: string;
  modifiedOnUtc: string;
  isDeleted: boolean;
}

export interface ResponseCalculateChargeCantPay {
  status: BalacenCertificateStatus;
  message: string;
}

// Generated by https://quicktype.io

export interface PayloadChargeBalance {
  charge: number;
  vat: number;
  alternateAccountId: string;
  chargeOption: number;
}
