export interface AddTransaction {
  beneficiaryName: string;
  bank_Operator: string;
  account_Phone: string;
  amount: number;
  currency: string;
  debitAccount: string;
  modeofPayment: string;
  paymentReason: string;
  narration: string;
  isValid: boolean;
  errors: string;
  debitAccountDetails: DebitAccountDetails;
  suspenseAccount?: string;
}

export interface BulkCharges {
  SuspenseAccount: string;
  BeneficiaryAccounts: string[];
  Currency: string;
  PaySystem: string;
}
export interface DebitAccountDetails {
  accountName: string;
  accountNumber: string;
  accountCurrency: string;
  accountStatus: string;
  availableBalance: number;
  effectiveBalance: string;
}

export interface CreateTicketPayload {
  associatedId: string;
  customerId: string;
  customerName: string;
  actionName: string;
  paymentOption: string;
  sendersAccountDetails: {
    accountName: string;
    accountNumber: string;
    accountCurrency: string;
    accountStatus: string;
    availableBalance: number;
    effectiveBalance: string;
  }[];
}

export interface UploadDoc {
  file: string;
  sendersDetails: SendersDetails;
}
export interface SendersDetails {
  accountName: string;
  accountNumber: string;
  accountCurrency: string;
  accountStatus: string;
  availableBalance: number;
  effectiveBalance: string;
}

export interface GetTransactionsResponse {
  statusMessage: string;
  statusCode: string;
  successful: boolean;
  responseObject: {
    paymentTransactions: {
      beneficiaryName: string;
      bank_Operator: string;
      account_Phone: string;
      amount: number;
      currency: string;
      rate: number;
      modeofPayment: string;
      paymentReason: string;
      narration: string;
      isValid: boolean;
      errors: string;
      transactionref: string;
      debitAccountDetails: {
        accountName: string;
        accountNumber: string;
        accountCurrency: string;
        accountStatus: string;
        availableBalance: number;
        effectiveBalance: string;
      };
    }[];
    paymentOption: string;
    documentRequired: boolean;
    documentUploaded: boolean;
    totalTransanctionAmount: number;
    totalChargeAmount: number;
  };
}

export type PaymentTransactions =
  GetTransactionsResponse['responseObject']['paymentTransactions'];

// Generated by https://quicktype.io

export interface TicketTransactionsResponse {
  responseObject: TicketTransactionsResponseObject[];
  statusCode: string;
  statusMessage: string;
  successful: boolean;
  errors: any[];
}

export interface TicketTransactionsResponseObject {
  suspenseAccount: null;
  totalAmount: number;
  bankId: null;
  paymentTransactions: PaymentTransaction[];
  transactionStatus: string;
  tranReference: string;
  transactionId: string;
  tranDate: string;
  ticketID: string;
}

export interface PaymentTransaction {
  accountNumber: string;
  amount: string;
  currency: string;
}
