import { Component,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  SimpleChanges, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { COMPAT_IMPORTS } from '../../../compat-barrel';
import { from, map, mergeMap, Subject, takeUntil } from 'rxjs';
import { AccountManagementService } from 'src/app/core/services/account-management/account-management.service';
import { AccountService } from 'src/app/core/services/account/account.service';
import { ImagePreviewModalComponent } from 'src/app/shared/components/customer-information/image-preview-modal/image-preview-modal.component';
import { MessageBoxType, ToastService } from 'src/app/shared/modules/toast';
import { ApiService } from '@app/shared/services/api.service';

// Generated by https://quicktype.io

export interface SupportDocuments {
  id: string;
  filename: string;
  uploadDate: string;
}

@Component({
  selector: 'app-known-agent-customer-image',
  templateUrl: './known-agent-customer-image.component.html',
  styleUrls: ['./known-agent-customer-image.component.scss'],
  imports: [COMPAT_IMPORTS],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]})
export class KnownAgentCustomerImageComponent
  implements OnInit, OnChanges, OnDestroy
{
  @Input() acc: any;
  @Input() CIF: any;
  @Input() supportDocuments!: SupportDocuments[];

  public customerPhoto: SafeResourceUrl | string =
    './assets/icons/icon-placeholder-potrait.svg';
  public customerPhotos: any = {};
  public customerPhoto2: SafeResourceUrl | string =
    './assets/icons/icon-placeholder-darker.svg';
  public customerSignature: SafeResourceUrl | string =
    './assets/icons/icon-placeholder-darker.svg';
  public customerSignature2: SafeResourceUrl | string =
    './assets/icons/icon-placeholder-darker.svg';

  private destroy$ = new Subject<any>();

  constructor(
    private accountManagementService: AccountManagementService,
    private accountService: AccountService,
    private toastService: ToastService,
    private domSanitizer: DomSanitizer,
    public dialog: MatDialog,
    private api: ApiService
  ) {}

  ngOnInit(): void {
    this.setDocuments();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes?.['acc']?.currentValue) {
      let accNumber: any = changes['acc'].currentValue;
      return this.fetchCustomerImagesSecondCall(accNumber);
    }

    if (changes?.['supportDocuments']?.currentValue) {
      this.setDocuments();
    }
  }

  previewDocument(obj: SupportDocuments, type: 'NewGen' | 'Blob' = 'Blob') {
    return this.api
      .postBlob('/v2/documents/download', {
        id: obj?.id?.toString(),
        service: type,
      })
      .pipe(
        mergeMap((stream: any) => {
          return from(
            new Promise((resolve, _) => {
              const isPDF =
                obj?.filename?.split('.')[1]?.toLowerCase() === 'pdf';
              const contentType = isPDF ? 'application/pdf' : 'octet/stream';
              const reader = new FileReader();
              reader.onloadend = () => resolve(reader.result);
              reader.readAsDataURL(new Blob([stream], { type: contentType }));
            })
          );
        }),
        map(data => {
          return {
            data,
            filename: obj.filename,
          };
        }),
        takeUntil(this.destroy$)
      );
  }

  fetchCustomerImagesSecondCall = (val: any) => {
    const customer = this.CIF
      ? { cif: this.CIF }
      : this.accountManagementService['getCustomer']();

    if (customer && customer.cif) {
      this.accountService['fetchPhoto'](
        {
          customerId: customer.cif,
          accountid: val,
        },
        'v1'
      )
        .subscribe({
          next: (result: any) => {
            if (!result.successful) {
              this.toastService.show(
                result.statusMessage,
                'Error',
                MessageBoxType.DANGER,
                5000,
                undefined,
                undefined,
                false
              );
              return;
            }

            const images = result.responseObject;
            this.accountManagementService['setCustomerImages'](images);
            this.mapImages([images[0]]);
          },
          error: (error: any) => {
            this.toastService.show(
              error.message,
              'Error',
              MessageBoxType.DANGER,
              5000,
              undefined,
              undefined,
              false
            );
          },
        });
    }
  };

  mapImages = (images: any) => {
    if (images.length > 0) {
      this.customerPhotos = images.map((v: any) => {
        return {
          photo: this.domSanitizer.bypassSecurityTrustUrl(
            'data:image/jpeg;base64,' + v?.returnedPhotographFiels
          ),
          signaturePhoto: this.domSanitizer.bypassSecurityTrustUrl(
            'data:image/jpeg;base64,' + v?.returnedSignatureField
          ),
        };
      });
    } else if (images.length === 0) {
      this.customerPhotos = null;
    }
  };

  displayImageModal = (source: any) => {
    const dialogRef = this.dialog.open(ImagePreviewModalComponent, {
      width: '600px',
    });

    dialogRef.componentInstance.imageSource = source;
  };

  fetchCustomerImages = (customer: any) => {
    if (customer && customer.cif) {
      this.accountService['fetchPhoto'](
        {
          customerId: customer.cif,
          accountid: this.acc,
        },
        'v1'
      )
        .subscribe(
          (result: any) => {
            if (!result.successful) {
              this.toastService.show(
                result.statusMessage,
                'Error',
                MessageBoxType.DANGER
              );
              return;
            }
            const images = result.responseObject;
            this.accountManagementService['setCustomerImages'](images);
            this.mapImages([images[0]]);
          },
          (error: any) => {
            this.toastService.show(
              error,
              'Error',
              MessageBoxType.DANGER,
              5000,
              undefined,
              undefined,
              false
            );
          }
        );
    }
  };

  private setDocuments() {
    const _supportDocuments = this.supportDocuments?.filter(data =>
      ['photo', 'signature'].includes(data.filename)
    );

    _supportDocuments?.forEach(doc => {
      if (doc.id)
        this.previewDocument(doc)
          .pipe()
          .subscribe((b64: any) => {
            const _data = { data: b64 };

            let key!: string;

            if (_data.data.filename.includes('photo')) {
              key = 'photo';
            } else if (_data.data.filename.includes('signature')) {
              key = 'signaturePhoto';
            }

            this.customerPhotos[key] = _data.data.data;
          });
    });
  }

  ngOnDestroy(): void {
    this.destroy$.next('');
    this.destroy$.complete();
  }
}
