// Generated by https://quicktype.io

export interface ICifInquiryResponse {
  statusMessage: string;
  statusCode: string;
  successful: boolean;
  responseObject: CifInquiryObject;
}

export interface CifInquiryObject {
  personalDetails?: PersonalDetails;
  companyDetails?: CompanyDetails;
  contactDetails: ContactDetails;
  physicalAddress: any;
  nextOfKin: NextOfKin;
  sourceOfIncome: SourceOfIncome;
  additionalInformation: AdditionalInformation;
  accountDetails: AccountDetails;
  identificationDetails: IdentificationDetail[];
}

export interface AccountDetails {
  bankId: string;
  accountId: string;
  accountManager: string;
  branchId: string;
  isSuspended: boolean;
}
// Generated by https://quicktype.io

export interface AdditionalInformation {
  eddCompletionDate: string;
  highRiskCategory: string;
  kycDate: string;
  kycReviewDate: string;
  minor: boolean;
  nextReviewDate: string;
  pepDescription: string;
  politicallyExposed: boolean;
  riskProfileScore: string;
  riskRating: string;
  secondaryRMId: string;
  staffEmployeeId: string;
  staffMember: boolean;
  submitForKYC: string;
}

export interface ContactDetails {
  phoneNumbers: PhoneNumber[];
  emailAddresses: EmailAdresses[];
  addresses: Address[];
}

export interface Address {
  addressId: string;
  county: string;
  constituency: string;
  district: string;
  division: string;
  location: string;
  subLocation: string;
  postalAddress: string;
  cityCode: string;
  city: string;
  village: string;
  estate: string;
  poBox: string;
  postalCode: string;
  stateProvince: string;
  addressType: string;
  preferred: boolean;
  building: string;
  currentPlaceOfResidence: string;
  addressStartDate: string;
  toBeDeleted: boolean;
}

export interface PhoneNumber {
  id: string;
  cityCode: string;
  countryCode: string;
  number: string;
  comment: string;
  phoneType: string;
  preferred: boolean;
  toBeDeleted: boolean;
  code: string;
}

// Generated by https://quicktype.io

export interface EmailAdresses {
  id: string;
  emailAddress: string;
  emailType: string;
  comment: null;
  preferred: boolean;
  toBeDeleted: boolean;
}

export interface IdentificationDetail {
  docType: string;
  issueDt: string;
  expiryDt: string;
  countryOfIssue: string;
  placeOfIssue: string;
  referenceNum: string;
  docCode: string;
  typeCode: string;
  desc: string;
  typeDesc: string;
  preferredUniqueId: boolean;
  prefUniqueId: boolean;
  idIssuedOrganisation: string;
  docTypeDesc: string;
  docDesc: string;
}

export interface NextOfKin {
  idType: string;
  idNumber: string;
  firstName: string;
  lastName: string;
  middleName: string;
  relation: string;
  phoneNumber: string;
}

export interface PersonalDetails {
  customerId: string;
  nationality: any;
  countryOfResidence: any;
  idType: string;
  idNumber: string;
  taxNumber: string;
  idSerialNumber: string;
  firstName: string;
  lastName: string;
  otherName: string;
  middleName: string;
  birthDate: string;
  gender: string;
  maritalStatus: string;
  krapInNumber: string;
  religion: string;
  placeOfBirth: string;
  region: string;
  preferredLanguageCode: string;
  nre: boolean;
  language: string;
}

export interface SourceOfIncome {
  miscellaneousId: string;
  employmentStatus: string;
  industry: string;
  sector: string;
  natureOfBusiness: string;
  occupation: string;
  monthlyIncome: string;
  profession: string;
  jobTitle: string;
}

export interface CompanyDetails {
  businessType: string;
  registrationNumber: string;
  documentsUploaded: boolean;
  customerId: string;
  countryOfResidence: string;
  companyName: string;
  krapInNumber: string;
  registrationDate: string;
  highRiskCategory: string;
  politicallyExposed: boolean;
  pepDesc: string;
}

export namespace CustomerDetail {
  export interface PersonalDetails {
    customerId: string;
    nationality: string;
    countryOfResidence: string;
    idType: string;
    idNumber: string;
    idSerialNumber?: any;
    firstName: string;
    lastName: string;
    middleName: string;
    birthDate: string;
    gender: string;
    maritalStatus: string;
    krapInNumber: string;
    religion: string;
    nre: boolean;
  }

  export interface PhoneNumber {
    id: string;
    cityCode: string;
    countryCode: string;
    number: string;
    comment?: any;
    phoneType: string;
    preferred: boolean;
    toBeDeleted: boolean;
  }

  export interface Address {
    addressId: string;
    county: string;
    constituency: string;
    district?: any;
    division?: any;
    location: string;
    subLocation?: any;
    postalAddress: string;
    cityCode: string;
    city: string;
    village: string;
    estate?: any;
    poBox?: any;
    postalCode: string;
    stateProvince?: any;
    addressType: string;
    preferred: boolean;
    building?: any;
    currentPlaceOfResidence?: any;
    addressStartDate: string;
    toBeDeleted: boolean;
  }

  export interface ContactDetails {
    phoneNumbers: PhoneNumber[];
    emailAddresses: any[];
    addresses: Address[];
  }

  export interface NextOfKin {
    idType?: any;
    idNumber?: any;
    firstName?: any;
    lastName?: any;
    middleName?: any;
    relation?: any;
    phoneNumber?: any;
  }

  export interface SourceOfIncome {
    miscellaneousId: string;
    employmentStatus: string;
    industry: string;
    sector: string;
    natureOfBusiness: string;
    occupation: string;
    monthlyIncome?: any;
    profession?: any;
    jobTitle: string;
    employed?: any;
    selfEmployed?: any;
    employerName?: any;
    employerContactNumber?: any;
    vertical1?: any;
    vertical2?: any;
    isicLevel1?: any;
    isicLevel2?: any;
    isicLevel3?: any;
    isicLevel4?: any;
    demandISIC1?: any;
    demandISIC2?: any;
    secondaryLevel?: any;
    secondaryISICLevel1?: any;
    secondaryISICLevel2?: any;
    secondaryISICLevel3?: any;
    secondaryISICLevel4?: any;
    secondaryDemandISIC1?: any;
    secondaryDemandISIC2?: any;
    climateCategory?: any;
    ecosystemCategory?: any;
    environmentalCategory?: any;
  }

  export interface AdditionalInformation {
    politicallyExposed: boolean;
    staffMember: boolean;
    staffEmployeeId?: any;
    minor: boolean;
    pepDescription?: any;
    eddCompletionDate?: any;
    highRiskCategory?: any;
    nextReviewDate?: any;
  }

  export interface AccountDetails {
    bankId: string;
    accountId?: any;
    accountManager: string;
    branchId: string;
    isSuspended: boolean;
  }

  export interface IdentificationDetail {
    docType: string;
    issueDt: string;
    expiryDt?: any;
    countryOfIssue: string;
    placeOfIssue: string;
    referenceNum: string;
    docCode?: any;
    typeCode?: any;
    desc?: any;
    typeDesc?: any;
    preferredUniqueId: boolean;
    prefUniqueId: boolean;
    idIssuedOrganisation?: any;
  }

  export interface RootObject {
    personalDetails: PersonalDetails;
    contactDetails: ContactDetails;
    physicalAddress?: any;
    nextOfKin: NextOfKin;
    sourceOfIncome: SourceOfIncome;
    additionalInformation: AdditionalInformation;
    accountDetails: AccountDetails;
    identificationDetails: IdentificationDetail[];
  }
}
