/**
 * Common country codes and names for non-operating countries
 * @see https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes#Non-ISO_members_and_non-members
 */
export const COMMON_COUNTRIES: { [key: string]: string } = {
  US: 'United States',
  GB: 'United Kingdom',
  CA: 'Canada',
  AU: 'Australia',
  ZA: 'South Africa',
  NG: 'Nigeria',
  GH: 'Ghana',
  ET: 'Ethiopia',
  EG: 'Egypt',
  MA: 'Morocco',
  DZ: 'Algeria',
  TN: 'Tunisia',
  LY: 'Libya',
  SD: 'Sudan',
  SN: 'Senegal',
  ML: 'Mali',
  BF: 'Burkina Faso',
  NE: 'Niger',
  TD: 'Chad',
  CF: 'Central African Republic',
  CM: 'Cameroon',
  GA: 'Gabon',
  GQ: 'Equatorial Guinea',
  ST: 'São Tomé and Príncipe',
  CV: 'Cape Verde',
  GM: 'Gambia',
  GW: 'Guinea-Bissau',
  GN: 'Guinea',
  SL: 'Sierra Leone',
  LR: 'Liberia',
  CI: 'Ivory Coast',
  BJ: 'Benin',
  TG: 'Togo',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
  BW: 'Botswana',
  LS: 'Lesotho',
  SZ: 'Swaziland',
  MZ: 'Mozambique',
  MW: 'Malawi',
  MG: 'Madagascar',
  MU: 'Mauritius',
  SC: 'Seychelles',
  KM: 'Comoros',
  DJ: 'Djibouti',
  SO: 'Somalia',
  ER: 'Eritrea',
  AO: 'Angola',
  NA: 'Namibia',
  FR: 'France',
  DE: 'Germany',
  IT: 'Italy',
  ES: 'Spain',
  PT: 'Portugal',
  NL: 'Netherlands',
  BE: 'Belgium',
  CH: 'Switzerland',
  AT: 'Austria',
  SE: 'Sweden',
  NO: 'Norway',
  DK: 'Denmark',
  FI: 'Finland',
  IS: 'Iceland',
  IE: 'Ireland',
  LU: 'Luxembourg',
  MT: 'Malta',
  CY: 'Cyprus',
  GR: 'Greece',
  BG: 'Bulgaria',
  RO: 'Romania',
  HU: 'Hungary',
  CZ: 'Czech Republic',
  SK: 'Slovakia',
  PL: 'Poland',
  LT: 'Lithuania',
  LV: 'Latvia',
  EE: 'Estonia',
  HR: 'Croatia',
  SI: 'Slovenia',
  BA: 'Bosnia and Herzegovina',
  RS: 'Serbia',
  ME: 'Montenegro',
  MK: 'North Macedonia',
  AL: 'Albania',
  XK: 'Kosovo',
  MD: 'Moldova',
  UA: 'Ukraine',
  BY: 'Belarus',
  RU: 'Russia',
  CN: 'China',
  JP: 'Japan',
  KR: 'South Korea',
  IN: 'India',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  LK: 'Sri Lanka',
  MV: 'Maldives',
  AF: 'Afghanistan',
  IR: 'Iran',
  IQ: 'Iraq',
  SY: 'Syria',
  LB: 'Lebanon',
  JO: 'Jordan',
  IL: 'Israel',
  PS: 'Palestine',
  SA: 'Saudi Arabia',
  AE: 'United Arab Emirates',
  KW: 'Kuwait',
  QA: 'Qatar',
  BH: 'Bahrain',
  OM: 'Oman',
  YE: 'Yemen',
  TR: 'Turkey',
  GE: 'Georgia',
  AM: 'Armenia',
  AZ: 'Azerbaijan',
  KZ: 'Kazakhstan',
  UZ: 'Uzbekistan',
  TM: 'Turkmenistan',
  KG: 'Kyrgyzstan',
  TJ: 'Tajikistan',
  MN: 'Mongolia',
  TH: 'Thailand',
  VN: 'Vietnam',
  LA: 'Laos',
  KH: 'Cambodia',
  MM: 'Myanmar',
  MY: 'Malaysia',
  SG: 'Singapore',
  BN: 'Brunei',
  ID: 'Indonesia',
  TL: 'Timor-Leste',
  PH: 'Philippines',
  BR: 'Brazil',
  AR: 'Argentina',
  CL: 'Chile',
  PE: 'Peru',
  CO: 'Colombia',
  VE: 'Venezuela',
  EC: 'Ecuador',
  BO: 'Bolivia',
  PY: 'Paraguay',
  UY: 'Uruguay',
  GY: 'Guyana',
  SR: 'Suriname',
  MX: 'Mexico',
  GT: 'Guatemala',
  BZ: 'Belize',
  SV: 'El Salvador',
  HN: 'Honduras',
  NI: 'Nicaragua',
  CR: 'Costa Rica',
  PA: 'Panama',
  CU: 'Cuba',
  JM: 'Jamaica',
  HT: 'Haiti',
  DO: 'Dominican Republic',
  TT: 'Trinidad and Tobago',
  BB: 'Barbados',
  LC: 'Saint Lucia',
  VC: 'Saint Vincent and the Grenadines',
  GD: 'Grenada',
  AG: 'Antigua and Barbuda',
  KN: 'Saint Kitts and Nevis',
  DM: 'Dominica',
  BS: 'Bahamas',
  NZ: 'New Zealand',
  FJ: 'Fiji',
  PG: 'Papua New Guinea',
  SB: 'Solomon Islands',
  VU: 'Vanuatu',
  NC: 'New Caledonia',
  WS: 'Samoa',
  TO: 'Tonga',
  KI: 'Kiribati',
  TV: 'Tuvalu',
  NR: 'Nauru',
  PW: 'Palau',
  FM: 'Micronesia',
  MH: 'Marshall Islands',
};

/**
 * Get country name by country code
 * @param countryCode - ISO 2-letter country code
 * @returns
 */
export function getCountryNameByCode(countryCode: string): string {
  return COMMON_COUNTRIES[countryCode] || countryCode;
}
