// Generated by https://quicktype.io
export interface IdentifyResponse {
  firstName: string;
  lastName: string;
  middleName: string;
  gender: string;
  nationality: string;
  birthDate: string;
  occupation: string;
  identityDocumentNumber: string;
  serialNumber: string;
  identityDocumentType: string;
  issueDate: string;
  issuingLocation: string;
  issuingAuthority: string;
}
