// Generated by https://quicktype.io

export interface UplodedDocument {
  documentName: string;
  documentDescription: string;
  name: string;
  size: string;
  success: boolean;
  mandatory: boolean;
  document: DocumentClass;
  icon: string;
  uploadedFile: any;
  fileName: string;
  fileSize: string;
  Url: string;
}

export interface DocumentClass {
  filename: string;
  format: string;
  data: string;
}
