// Newgen docs
export const JOINT_ACCOUNT_LETTER_DOCUMENT_NAME = 'joint account letter';
export const UNEXPIRED_VOTERS_ID_DOCUMENT_NAME = 'Voter Id Card';
export const CENTRAL_BANK_FORM_DOCUMENT_NAME = 'Central Bank Form';
export const APPLICATION_FORM_DOCUMENT_NAME = 'Application Form';
export const NATIONAL_ID_DOCUMENT_NAME = 'nationalId';
export const KENYAN_PASSPORT_DOCUMENT_NAME = 'KenyanPassport';
export const DRIVERS_LICENSE_DOCUMENT_NAME = 'drivingLicense';
export const MILITARY_ID_DOCUMENT_NAME = 'militaryID';
export const KRA_PIN_CERTIFICATE_DOCUMENT_NAME = 'KRAPin';
export const FORM_DOCUMENT_NAME = 'Form';
export const ACCOUNT_OPENING_FORM_DOCUMENT_NAME =
  'individualAccountOpeningForm';
export const FOREIGN_PASSPORT_DOCUMENT_NAME = 'PassportForeignDocument';
export const WORK_PERMIT_DOCUMENT_NAME = 'Permit';
export const PASSPORT_SCREENING_RESULTS_DOCUMENT_NAME =
  'PassportScreeningResults';
export const INTRODUCTION_LETTER_DOCUMENT_NAME = 'IntroductionLetter';
export const ALIEN_ID_DOCUMENT_NAME = 'alienId';
export const REFUGEE_ID_CARD_DOCUMENT_NAME = 'RefugeeIDCardDocument';
export const ADDITIONAL_DOCUMENT_NAME = 'AdditionalFileDocument_';
export const EDD_FORM_NAME = 'EDD Form';
export const FATCA_DOCUMENT_NAME = 'fatca';
export const BIRTH_CERTIFICATE_NAME = 'Birth Certificate';
export const UNHCR_PROOF = 'UNHCRProof';
export const PROOF_OF_RESIDENCE = 'ProofOfResidence';

// Finacle docs
export const PASSPORT_PHOTO_DOCUMENT_NAME = 'Picture';
export const SIGNATURE_DOCUMENT_NAME = 'Signature';

// upload params
export const MAX_DOCUMENTS_PER_CALL = 5;

export const DEFAULT_MAX_FILE_SIZE = 1 * 1024 * 1024;
export const DEFAULT_MAX_FILE_SIZE_FINACLE = 100 * 1024;

// non-mandatory documents
export const NON_MANDATORY_DOCUMENTS = [
  ALIEN_ID_DOCUMENT_NAME,
  WORK_PERMIT_DOCUMENT_NAME,
];

export const JPEG_ALLOWED_DOCUMENTS = [
  PASSPORT_PHOTO_DOCUMENT_NAME,
  SIGNATURE_DOCUMENT_NAME,
  JOINT_ACCOUNT_LETTER_DOCUMENT_NAME,
  UNEXPIRED_VOTERS_ID_DOCUMENT_NAME,
  CENTRAL_BANK_FORM_DOCUMENT_NAME,
  APPLICATION_FORM_DOCUMENT_NAME,
  NATIONAL_ID_DOCUMENT_NAME,
  KENYAN_PASSPORT_DOCUMENT_NAME,
  DRIVERS_LICENSE_DOCUMENT_NAME,
  MILITARY_ID_DOCUMENT_NAME,
  KRA_PIN_CERTIFICATE_DOCUMENT_NAME,
  FORM_DOCUMENT_NAME,
  ACCOUNT_OPENING_FORM_DOCUMENT_NAME,
  FOREIGN_PASSPORT_DOCUMENT_NAME,
  WORK_PERMIT_DOCUMENT_NAME,
  PASSPORT_SCREENING_RESULTS_DOCUMENT_NAME,
  INTRODUCTION_LETTER_DOCUMENT_NAME,
  ALIEN_ID_DOCUMENT_NAME,
  REFUGEE_ID_CARD_DOCUMENT_NAME,
  ADDITIONAL_DOCUMENT_NAME,
  EDD_FORM_NAME,
  FATCA_DOCUMENT_NAME,
  JOINT_ACCOUNT_LETTER_DOCUMENT_NAME,
  ACCOUNT_OPENING_FORM_DOCUMENT_NAME,
  PROOF_OF_RESIDENCE,
  UNHCR_PROOF,
];

export const PDF_ALLOWED_DOCUMENTS = [
  JOINT_ACCOUNT_LETTER_DOCUMENT_NAME,
  UNEXPIRED_VOTERS_ID_DOCUMENT_NAME,
  CENTRAL_BANK_FORM_DOCUMENT_NAME,
  APPLICATION_FORM_DOCUMENT_NAME,
  NATIONAL_ID_DOCUMENT_NAME,
  KENYAN_PASSPORT_DOCUMENT_NAME,
  DRIVERS_LICENSE_DOCUMENT_NAME,
  MILITARY_ID_DOCUMENT_NAME,
  KRA_PIN_CERTIFICATE_DOCUMENT_NAME,
  FORM_DOCUMENT_NAME,
  ACCOUNT_OPENING_FORM_DOCUMENT_NAME,
  FOREIGN_PASSPORT_DOCUMENT_NAME,
  WORK_PERMIT_DOCUMENT_NAME,
  PASSPORT_SCREENING_RESULTS_DOCUMENT_NAME,
  INTRODUCTION_LETTER_DOCUMENT_NAME,
  ALIEN_ID_DOCUMENT_NAME,
  REFUGEE_ID_CARD_DOCUMENT_NAME,
  ADDITIONAL_DOCUMENT_NAME,
  EDD_FORM_NAME,
  FATCA_DOCUMENT_NAME,
  JOINT_ACCOUNT_LETTER_DOCUMENT_NAME,
  ACCOUNT_OPENING_FORM_DOCUMENT_NAME,
  PROOF_OF_RESIDENCE,
  UNHCR_PROOF,
];

// urls
export const UPLOAD_URL_V1 = '/v1/documents/submit';
export const UPLOAD_URL_V2 = '/v2/documents/submit';
