export const ACC_CHANNELS: any[] = [
  {
    id: '',
    channelId: '',
    channelBlockReason: '',
    channel: 'Web',
    subChannel: '',
    level: -1,
    isChannelActive: false,
    isChannelBlocked: true,
    blockedReason: null,
    channelCreatedOn: null,
    channelModifiedOn: null,
    passcodeInfo: null,
  },
  {
    id: '',
    channelId: '',
    channelBlockReason: '',
    channel: 'Mobile',
    subChannel: 'iOS',
    level: -1,
    isChannelActive: false,
    isChannelBlocked: true,
    blockedReason: null,
    channelCreatedOn: null,
    channelModifiedOn: null,
    passcodeInfo: null,
  },
  {
    id: '',
    channelId: '',
    channelBlockReason: '',
    channel: 'Mobile',
    subChannel: 'Android',
    level: -1,
    isChannelActive: false,
    isChannelBlocked: true,
    blockedReason: null,
    channelCreatedOn: null,
    channelModifiedOn: null,
    passcodeInfo: null,
  },
  {
    id: '',
    channelId: '',
    channelBlockReason: '',
    channel: 'USSD',
    subChannel: '',
    level: -1,
    isChannelActive: false,
    isChannelBlocked: true,
    blockedReason: null,
    channelCreatedOn: null,
    channelModifiedOn: null,
    passcodeInfo: null,
  },
  {
    id: '',
    channelId: '',
    channelBlockReason: '',
    channel: 'Chatbot',
    subChannel: '',
    level: -1,
    isChannelActive: false,
    isChannelBlocked: true,
    blockedReason: null,
    channelCreatedOn: null,
    channelModifiedOn: null,
    passcodeInfo: null,
  },
];
