export interface ITicketRoute {
  actionFlow: string[];
  statuses: string[];
  path: string;
  host: string | null;
}

export enum ActionFlows {
  // Onboarding App
  MINOR_ONBOARDING_V2 = 'MinorOnboardingV2',
  MINOR_ONBOARDING_V2_CD = 'MinorOnboardingV2CD',
  MINOR_ONBOARDING_V2_RW = 'MinorOnboardingV2RW',
  MINOR_ONBOARDING_V2_TZ = 'MinorOnboardingV2TZ',
  JOINT_ACCOUNT_CREATION = 'JointAccountCreation',
  BUSINESS_ACCOUNT = 'BusinessAccountFlow',
  BUSINESS_ACCOUNT_DDE = 'OpenBusinessAccountDDEFlow',
  PERSONAL_ACCOUNT = 'PersonalAccountFlow',
  PERSONAL_ACCOUNT_V2 = 'PersonalAccountFlowV2',
  PERSONAL_ACCOUNT_V2_TZ = 'PersonalAccountFlowV2TZ',
  PERSONAL_ACCOUNT_V2_CD = 'PersonalAccountFlowV2CD',
  ONBOARDING_DOCUMENTS = 'OnBoardingDocumentsFlow',
  JOINT_ACCOUNT = 'JointAccountFlow',
  INDIVIDUAL_CIF_UPDATE = 'UpdateCifDataFlow',
  INDIVIDUAL_CIF_UPDATESS = 'UpdateCifDataFlowSS',
  INDIVIDUAL_CIF_UPDATECD = 'UpdateCifDataFlowCD',
  ENTITY_CIF_UPDATE = 'UpdateEntityCifDataFlow',
  CREATE_MINOR_ACCOUNT = 'CreateMinorAccountFlow',
  CREATE_CIF = 'ActionFlowDDECreateCif',
  CREATE_CIF_DDE = 'ActionFlowDDECreateCifEdd',
  RW_JOINT_ACCOUNT_CREATION = 'RWJointAccountCreation',
  TZ_JOINT_ACCOUNT_CREATION = 'TZJointAccountCreation',
  CARD_LIMIT_AMENDMENT = 'CardLimitAmendment',
  UG_JOINT_ACCOUNT_CREATION = 'UGJointAccountCreation',
  // OpenAccountDDEEddFlow,
  // OpenAccountDDEExistingCustomerEddFlow,
  // OpenAccountDDEExistingCustomerFlow,
  // OpenAccountDDEFlow,
  // OpenAccountOtherDocQDEEddFlow,
  // OpenAccountOtherDocQDEFlow,
  // OpenAccountQDEEddFlow,
  // OpenAccountQDEExistingCustomerEddFlow,
  // OpenAccountQDEExistingCustomerFlow,
  // OpenAccountQDEFlow,
  // OpenJointAccountQDEFlow,

  // 360 App
  VIEW_CUSTOMER_PROFILE = 'ViewProfileFlow',
  ADD_KNOW_AGENT = 'AddKnownAgentFlow',
  REMOVE_KNOW_AGENT = 'RemoveKnownAgentFlow',
  AMENDKNOWNAGENTFLOW = 'AmendKnownAgentFlow',
  ADD_SIGNATORY = 'AddSignatoryFlow',
  REMOVE_SIGNATORY = 'RemoveSignatoryFlow',
  REQUEST_ACCOUNT_BALANCE = 'RequestAccountBalanceFlow',
  REQUEST_ACCOUNT_STATEMENT = 'RequestAccountStatementFlow',
  ADDITIONAL_ACCOUNT = 'AddAdditionalAccountFlow',
  CHANGE_ACCOUNT_MANDATE = 'ChangeMandateFlow',
  ACTIVATE_ACCOUNT = 'ActivateAccountFlow',
  ADDITIONAL_ENTITY_ACCOUNT = 'AdditionalEntityAccountFlow',
  ADD_STAKEHOLDER = 'AddStakeholderFlow',
  BREAK_DEPOSIT = 'BreakDepositFlow',
  BULK_PAYMENT_FILE_UPLOAD = 'BulkPaymentFileUploadFlow',
  BULK_PAYMENT_MANUAL_ENTITY = 'BulkPaymentManualEntryFlow',
  CALL_DEPOSIT = 'CallDepositFlow',
  PERSONAL_ACCOUNT_V2_UG = 'PersonalAccountFlowV2UG',
  ENTITY_ACCOUNTFLOW_V3 = 'EntityAccountFlowV3',
  ENTITY_ACCOUNTFLOW_CD_V3 = 'EntityAccountFlowCDV3',
  // MoveMoneyFlow,
  // StandingOrderCreateFlow,
  // StandingOrderDeleteFlow,
  // StandingOrderUpdateFlow,
  // RequestBankersChequeFlow,
  // RequestBranchCardLimitFlow,
  // RequestBranchCardRequestFlow,
  // RequestBranchCardRestockFlow,
  // RequestChequeBookFlow,
  // StopChequeBookRequestFlow,
  // CustomerProfileFlow,
  // CustomerRegistrationFlow,

  // Move Money Actions
  CASH_REQUEST_202 = 'CashRequest202Flow',
  CASH_REQUEST_299_DEPOSIT = 'CashRequest299DepositFlow',
  CASH_REQUEST_299_WITHDRAW = 'CashRequest299WithdrawFlow',
  CASH_REQUEST_CANCELLATION_299 = 'CashRequestCancellation299Flow',
  CASH_REQUEST_NORMAL_299 = 'CashRequestNormal299Flow',
  ADD_STAKEHOLDER_DDE = 'AddStakeHolderDDEFlow',
  ADD_STAKEHOLDER_EDD = 'AddStakeholderEddFlow',
  CUSTODIAN_END_OF_DAY = 'CustodianEndOfDayFlow',
  CUSTODIAN_START_OF_DAY = 'CustodianStartOfDayFlow',
  CUSTOMER_FUND_TRANSFER_103 = 'CustomerFundTransfer103',
  REMITTANCE_CANCELLATION_MT192 = 'RCMT192CancellationRecallFlow',
  REMITTANCE_CONFIRMATION_MT192 = 'RCMT199ConfirmationMT103Flow',
  REMITTANCE_CONFIRMATION_WITH_CORRESPONDENCE_MT192 = 'RCMT199WithCorrespondentFlow',
  BLOCK_CARD = 'BlockCard',
  UNBLOCK_CARD = 'UnblockCard',
  // "RCMT199ProvisionFlow",

  // Admin Portal Actions
  CARD_END_OF_DAY = 'CardEndOfDay',
  // TellerDeposit,
  // TellerEndOfDay,
  // TellerSpecialStartOfDay,
  // TellerStartOfDayContinuing,
  // TellerStartOfDayForeignCurrency,
  // TellerStartOfDayNew,
  // TellerWithDraw,
  // NotificationCategory,
  // NotificationTemplate,
  // NotificationType,
  // NotificationUserSegment,
  // UpdateChequeBookRequestFlow,
  // CountryOperation,
  // DepartmentOperation,
  // PermissionOperation,
  // RoleOperation,
  // UserOperation,

  // OTHERS
  // BillCustomerRequest,
  // CustomerDepositFlow,
  // CustomerWithDrawFlow,
  // DispatchModeFlow,
  // FixedDepositFlow,
  // HighValueTransactionFlow,
  // IndividualSignatureFlow,
  // InProcessDormantAccountFlow,
  // JointSignatureFlow,
  // OpenCDSCAccountFlow,
  // ProfileRequestFlow,
  // SanctionedCustomerFlow,
  // ServiceRequestBCDCFlow,
  // ServiceRequestFlow,
  // SpecialProjectKCEP,
  // StatementFlow,
  // SubmitNewCategory,
  // SubmitNewFeature,
  // SubmitNewService,
  // ToogleServiceStatus,
  // UpdateSDService,
  // UserCreationFlow,
  // ViewProfileFlow
}

export const AdminPortalActionFlows: string[] = [
  'BlockCardFlow',
  'CardEndOfDay',
  'TellerDeposit',
  'TellerEndOfDay',
  'TellerSpecialStartOfDay',
  'TellerStartOfDayContinuing',
  'TellerStartOfDayForeignCurrency',
  'TellerStartOfDayNew',
  'TellerWithDraw',
  'NotificationCategory',
  'NotificationTemplate',
  'NotificationType',
  'NotificationUserSegment',
  'UpdateChequeBookRequestFlow',
  'CountryOperation',
  'DepartmentOperation',
  'PermissionOperation',
  'RoleOperation',
  'UserOperation',
  'LimitsOperation',
  'ToogleServiceStatus',
  'SubmitNewService',
  'SubmitNewCategory',
  'SubmitNewFeature',
  'UpdateSDService',
  'GlobalLimitUpdateFlow',
  'GlobalLimitCreateFlow',
  'Mt598',
  'OrgUnitOperations',
  'AddMerchantToList',
  'RemoveMerchantFromList',
  'ReassignTickets',
  'LimitTypeCreateFlow',
  'BlockCardFlow',
  'CardEndOfDay',
  'TellerDeposit',
  'TellerEndOfDay',
  'TellerSpecialStartOfDay',
  'TellerStartOfDayContinuing',
  'TellerStartOfDayForeignCurrency',
  'TellerStartOfDayNew',
  'TellerWithDraw',
  'NotificationCategory',
  'NotificationTemplate',
  'NotificationType',
  'NotificationUserSegment',
  'UpdateChequeBookRequestFlow',
  'CountryOperation',
  'DepartmentOperation',
  'PermissionOperation',
  'RoleOperation',
  'UserOperation',
  'LimitsOperation',
  'ToogleServiceStatus',
  'SubmitNewService',
  'SubmitNewCategory',
  'SubmitNewFeature',
  'UpdateSDService',
  'GlobalLimitUpdateFlow',
  'GlobalLimitCreateFlow',
  'Mt598',
  'OrgUnitOperations',
  'AddMerchantToList',
  'RemoveMerchantFromList',
  'ReassignTickets',
  'LimitTypeCreateFlow',
  'DestroyChequeFlow',
];

export const OnboardingActionFlows: string[] = [
  ActionFlows.JOINT_ACCOUNT_CREATION,
  ActionFlows.PERSONAL_ACCOUNT,
  ActionFlows.PERSONAL_ACCOUNT_V2,
  ActionFlows.PERSONAL_ACCOUNT_V2_TZ,
  ActionFlows.PERSONAL_ACCOUNT_V2_CD,
  ActionFlows.PERSONAL_ACCOUNT_V2_UG,
  ActionFlows.ONBOARDING_DOCUMENTS,
  ActionFlows.BUSINESS_ACCOUNT,
  ActionFlows.BUSINESS_ACCOUNT_DDE,
  ActionFlows.JOINT_ACCOUNT,
  ActionFlows.INDIVIDUAL_CIF_UPDATE,
  ActionFlows.INDIVIDUAL_CIF_UPDATESS,
  ActionFlows.ENTITY_ACCOUNTFLOW_V3,
  ActionFlows.ENTITY_ACCOUNTFLOW_CD_V3,
  ActionFlows.ENTITY_CIF_UPDATE,
  ActionFlows.MINOR_ONBOARDING_V2,
  ActionFlows.MINOR_ONBOARDING_V2_RW,
  ActionFlows.MINOR_ONBOARDING_V2_TZ,
  ActionFlows.MINOR_ONBOARDING_V2_CD,
  'PersonalFlowCifOnlyV2',
  'PersonalFlowCifOnlyV2UG',
  'PersonalFlowCifOnlyV2RW',
  'PersonalAccountFlowV2RW',
  'PersonalFlowCifOnlyV2CD',
  'PersonalFlowCifOnlyV2SS',
  'PersonalFlowCifOnlyV2TZ',
  'CreateMinorAccountFlow',
  'ActionFlowDDECreateCif',
  'ActionFlowDDECreateCifEdd',
  'OpenAccountDDEEddFlow',
  'OpenAccountDDEExistingCustomerEddFlow',
  'OpenAccountDDEExistingCustomerFlow',
  'OpenAccountDDEFlow',
  'OpenAccountOtherDocQDEEddFlow',
  'OpenAccountOtherDocQDEFlow',
  'OpenAccountQDEEddFlow',
  'OpenAccountQDEExistingCustomerEddFlow',
  'OpenAccountQDEExistingCustomerFlow',
  'OpenAccountQDEFlow',
  'OpenBusinessAccountDDEFlow',
  'OpenBusinessAccountFlow',
  'OpenJointAccountQDEFlow',
  'BusinessAccountFlow',
  'CreateCifFlow',
  'CDJointAccountCreation',
  'TransactionDocumentsSwiftFlow',
  'TransactionDocumentsCashFlow',
  'KycDocumentsPersonalFlow',
  ActionFlows.RW_JOINT_ACCOUNT_CREATION,
  ActionFlows.TZ_JOINT_ACCOUNT_CREATION,
  ActionFlows.UG_JOINT_ACCOUNT_CREATION,
  'PersonalAccountFlowV2RW',
  'EdrmsDocumentsRetrievalFlowSoft',
  'EdrmsDocumentsRetrievalFlowHard',
  'EdrmsDocumentsRetrievalFlowHybrid',
];

export const Customer360ActionFlows: string[] = [
  'RequestBranchCardRequestFlow',
  'RequestBranchCardRestockFlow',
  'AddAdditionalAccountV2FlowUG',
  'ChangeSignatureAndPhotoV2',
  'JointSignatureFlow',
  'IndividualSignatureFlow',
  'BlockCard',
  'UnlockCard',
  ActionFlows.UNBLOCK_CARD,
  ActionFlows.BLOCK_CARD,
  'CardLimitAmendment',
  'RequestChequeBookFlowV2',
  'IssueChequeBookFlow',
  'StopChequeFlow',
  'ViewProfileFlow',
  'SkipBio',
  'AddSignatoryV2',
  'RemoveSignatoryV2',
  'AddKnownAgentFlow',
  'AddKnownAgentFlowV2',
  'RemoveKnownAgentFlow',
  'AmendKnownAgentFlow',
  'AddSignatoryFlow',
  'RemoveSignatoryFlow',
  'RequestAccountBalanceFlow',
  'RequestAccountStatementFlow',
  'RequestAccountStatementFlowV2',
  'AddAdditionalAccountFlow',
  'ChangeMandateFlow',
  'ActivateAccountFlow',
  'ActivateAccountFlowV2',
  'AddStakeholderFlow',
  'BreakDepositFlow',
  'BulkPaymentFileUploadFlow',
  'BulkPaymentManualEntryFlow',
  'CallDepositFlow',
  'MoveMoneyFlow',
  'StandingOrderCreateFlow',
  'StandingOrderDeleteFlow',
  'StandingOrderUpdateFlow',
  'RequestBankersChequeFlow',
  'RequestBranchCardLimitFlow',
  'RequestChequeBookFlow',
  'StopChequeBookRequestFlow',
  'CustomerProfileFlow',
  'CustomerRegistrationFlow',
  'SoftDeleteFlow',
  'TransactionLimitFlow',
  'LimitPersonalization',
  'ModifyBankersChequeBookFlow',
  'RequestForeignDraftFlow',
  'DeLinkAccountFlow',
  'RestoreAccount',
  'UpdateScheduledPayment',
  'CancelScheduledPayment',
  'RestrictAccount',
  'DeLinkPaypalAccountFlow',
  'AddAdditionalAccountV2Flow',
  'ChangeMandateFlowV2',
  'ChangeModeOfOperationFlow',
  'InstantCardIssuance',
  'PremiumCardIssuance',
  'BuyFloatOptInAndOut',
  'ImtHighValueTransaction',
  'NotificationPreferenceOptInOut',
  'AdditionalEntityAccountFlow',
];

export const MoveMoneyActionFlows: string[] = [
  ActionFlows.CASH_REQUEST_202,
  ActionFlows.CASH_REQUEST_299_DEPOSIT,
  ActionFlows.CASH_REQUEST_299_WITHDRAW,
  ActionFlows.CASH_REQUEST_CANCELLATION_299,
  ActionFlows.CASH_REQUEST_NORMAL_299,
  ActionFlows.ADD_STAKEHOLDER_DDE,
  ActionFlows.ADD_STAKEHOLDER_EDD,
  ActionFlows.CUSTODIAN_END_OF_DAY,
  ActionFlows.CUSTODIAN_START_OF_DAY,
  ActionFlows.CUSTOMER_FUND_TRANSFER_103,
  ActionFlows.REMITTANCE_CANCELLATION_MT192,
  ActionFlows.REMITTANCE_CONFIRMATION_MT192,
  ActionFlows.REMITTANCE_CONFIRMATION_WITH_CORRESPONDENCE_MT192,
  'RCMT199ProvisionFlow',
];

export const routesConfig: ITicketRoute[] = [
  {
    actionFlow: [
      'RequestAccountStatementFlow',
      'RequestAccountStatementFlowV2',
    ],
    statuses: ['SubmittedToChecker', 'Returned', 'Completed'],
    path: '/tickets/account-statement-ticket',
    host: null,
  },
  {
    actionFlow: [
      'IndividualSignatureFlow',
      'JointSignatureFlow'
    ],
    statuses: ['SubmittedToChecker', 'Returned'],
    path: '/tickets/change-of-signature-checker',
    host: null,
  },
];
