import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'transformPhoneNumber',
})
export class TransformPhoneNumberPipe implements PipeTransform {
  transform(
    phoneNumbers:
      | {
          id: string;
          cityCode: string;
          countryCode: string;
          number: string;
          comment: any;
          phoneType: string;
          preferred: boolean;
          toBeDeleted: boolean;
        }[] /*INDIVIDIAL PHONE INTERFACE*/
      | {
          id: string;
          code: string;
          number: string;
          comment: null;
          phoneType: string;
          preferred: boolean;
        }[] /*ENTITY PHONE INTERFACE*/,
    preferred: 'PRIMARY' | 'SECONDARY' = 'PRIMARY'
  ): string {
    const _preferred = preferred === 'PRIMARY' ? true : false;

    const found = phoneNumbers
      .map((item: any) => {
        return {
          countryCode: item?.code ? item?.code : item?.cityCode,
          number: item.number,
          preferred: item.preferred,
        };
      })
      .find(phone => phone.preferred === _preferred);
    if (found) return `${found.countryCode} ${found.number}`;
    else return '';
  }
}

// Generated by https://quicktype.io

export interface D {}
